### ISSUE TITLE
RangeError: attempt to write beyond buffer bounds

### ISSUE THREAD

**Issue by ghost** [mafintosh/changesdown#1]
I'm getting an error inside of changesdown:

```
buffer.js:343
    throw new RangeError('attempt to write beyond buffer bounds');
          ^
RangeError: attempt to write beyond buffer bounds
    at Buffer.write (buffer.js:343:11)
    at Object.exports.string.encode (/home/substack/projects/changes-index/node_modules/changesdown/node_modules/protocol-buffers/encodings.js:64:12)
    at Object.encode (eval at <anonymous> (/home/substack/projects/changes-index/node_modules/changesdown/node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:8:10)
    at ChangesDOWN._batch (/home/substack/projects/changes-index/node_modules/changesdown/changesdown.js:104:25)
    at AbstractLevelDOWN.batch (/home/substack/projects/changes-index/node_modules/changesdown/node_modules/abstract-leveldown/abstract-leveldown.js:162:17)
    at /home/substack/projects/changes-index/node_modules/changesdown/node_modules/levelup/node_modules/deferred-leveldown/deferred-leveldown.js:16:19
    at Array.forEach (native)
    at DeferredLevelDOWN.setDb (/home/substack/projects/changes-index/node_modules/changesdown/node_modules/levelup/node_modules/deferred-leveldown/deferred-leveldown.js:15:20)
    at /home/substack/projects/changes-index/node_modules/changesdown/node_modules/levelup/lib/levelup.js:120:15
    at /home/substack/projects/changes-index/node_modules/changesdown/changesdown.js:80:11
```

from this code:

``` js
var level = require('level');
var sublevel = require('subleveldown');
var changes = require('changes-feed');
var changesdown = require('changesdown');

var up = level('test.db', { valueEncoding: 'json' });
var feed = changes(sublevel(up, 'feed'));
var db = changesdown(sublevel(up, 'db'), feed);

db.batch([
    { type: 'put', key: 'abc123', value: { type: 'user', name: 'substack' } }
], ready);

function ready () {
   console.log('ok'); 
}
```

but when I change the value in the batch to be a string instead of an object, the program doesn't crash.

versions:

```
$ npmlv
{
    "changes-feed": "1.0.0",
    "changesdown": "2.2.1",
    "inherits": "2.0.1",
    "isarray": "0.0.1",
    "level": "0.18.0",
    "level-change-processor": "1.0.0",
    "subleveldown": "1.1.0",
    "tape": "3.5.0"
}
```

**Comment by mafintosh** [comment]
Since you are writing JSON to the levelup produced by changesdown you need to set `valueEncoding: 'json'`.

``` js
var db = changesdown(sublevel(up, 'db'), feed, {valueEncoding: 'json'})

db.batch([
    { type: 'put', key: 'abc123', value: { type: 'user', name: 'substack' } }
], ready);
```

or

``` js
db.batch([
    { type: 'put', key: 'abc123', value: { type: 'user', name: 'substack' }, valueEncoding: 'json' }
], ready);
```

**Comment by mafintosh** [comment]
(the error message produced by changesdown could be nicer though)

**Comment by mafintosh** [comment]
actually this wasn't documented so added a section about this to the readme as well, https://github.com/mafintosh/changesdown#api
